-- LeadFlow / LM Studio
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create table if not exists public.leads (
  id text primary key,
  place_id text,
  name text not null,
  phone text,
  website text,
  site_quality text not null default 'none',
  rating numeric(3,2) not null default 0,
  reviews integer not null default 0,
  category text,
  address text,
  city text,
  state text,
  maps_url text,
  status text not null default 'Não contatado',
  notes text,
  followup date,
  franchise boolean not null default false,
  sent_at timestamptz,
  replied_at timestamptz,
  last_contact_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists leads_place_id_unique
  on public.leads(place_id) where place_id is not null and place_id <> '';
create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_followup_idx on public.leads(followup);
create index if not exists leads_updated_at_idx on public.leads(updated_at desc);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.leads(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  type text not null,
  description text,
  created_at timestamptz not null default now()
);
create index if not exists activities_lead_created_idx on public.activities(lead_id, created_at desc);

create table if not exists public.app_settings (
  id integer primary key check (id = 1),
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.activities enable row level security;
alter table public.app_settings enable row level security;

-- CRM privado: somente usuários autenticados no seu projeto Supabase.
-- Para equipe, crie usuários manualmente em Authentication > Users e mantenha signup público desativado.
drop policy if exists "authenticated_read_leads" on public.leads;
create policy "authenticated_read_leads" on public.leads for select to authenticated using (true);
drop policy if exists "authenticated_insert_leads" on public.leads;
create policy "authenticated_insert_leads" on public.leads for insert to authenticated with check (true);
drop policy if exists "authenticated_update_leads" on public.leads;
create policy "authenticated_update_leads" on public.leads for update to authenticated using (true) with check (true);
drop policy if exists "authenticated_delete_leads" on public.leads;
create policy "authenticated_delete_leads" on public.leads for delete to authenticated using (true);

drop policy if exists "authenticated_read_activities" on public.activities;
create policy "authenticated_read_activities" on public.activities for select to authenticated using (true);
drop policy if exists "authenticated_insert_activities" on public.activities;
create policy "authenticated_insert_activities" on public.activities for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "authenticated_read_settings" on public.app_settings;
create policy "authenticated_read_settings" on public.app_settings for select to authenticated using (true);
drop policy if exists "authenticated_insert_settings" on public.app_settings;
create policy "authenticated_insert_settings" on public.app_settings for insert to authenticated with check (true);
drop policy if exists "authenticated_update_settings" on public.app_settings;
create policy "authenticated_update_settings" on public.app_settings for update to authenticated using (true) with check (true);

insert into public.app_settings(id, settings)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

-- Realtime para sincronizar alterações entre computadores.
do $$
begin
  alter publication supabase_realtime add table public.leads;
exception
  when duplicate_object then null;
end $$;
